config/routes.rb
Rails.application.routes.draw do
  resources :entregas
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrega.rb
class Entrega < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entregas_controller.rb
class EntregasController < ApplicationController
  before_action :set_entrega, only: [:show, :edit, :update, :destroy]

  # GET /entregas
  # GET /entregas.json
  def index
    @entregas = Entrega.all
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'entregas/entrega', pdf:'entrega', layout:'entrega.html'}
    end
  end

  # GET /entregas/1
  # GET /entregas/1.json
  def show
  end

  # GET /entregas/new
  def new
    @entrega = Entrega.new
  end

  # GET /entregas/1/edit
  def edit
  end

  # POST /entregas
  # POST /entregas.json
  def create
    @entrega = Entrega.new(entrega_params)

    respond_to do |format|
      if @entrega.save
        format.html { redirect_to @entrega, notice: 'Entrega was successfully created.' }
        format.json { render :show, status: :created, location: @entrega }
      else
        format.html { render :new }
        format.json { render json: @entrega.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entregas/1
  # PATCH/PUT /entregas/1.json
  def update
    respond_to do |format|
      if @entrega.update(entrega_params)
        format.html { redirect_to @entrega, notice: 'Entrega was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrega }
      else
        format.html { render :edit }
        format.json { render json: @entrega.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entregas/1
  # DELETE /entregas/1.json
  def destroy
    @entrega.destroy
    respond_to do |format|
      format.html { redirect_to entregas_url, notice: 'Entrega was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrega
      @entrega = Entrega.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrega_params
      params.require(:entrega).permit(:ticket, :asegurado, :medico, :hospital, :coaseguro, :icd, :ctp, :ctp2, :folio, :reclamacion, :ingreso, :solicitud, :fecha_even)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'products/entrega', pdf:'entrega', layout:'entrega.html'}
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :pricing)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entregas_helper.rb
module EntregasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/entregas/_form.html.erb
<%= form_with(model: entrega, local: true) do |form| %>
  <% if entrega.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entrega.errors.count, "error") %> prohibited this entrega from being saved:</h2>

      <ul>
        <% entrega.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticket %>
    <%= form.text_field :ticket %>
  </div>

  <div class="field">
    <%= form.label :asegurado %>
    <%= form.text_field :asegurado %>
  </div>

  <div class="field">
    <%= form.label :medico %>
    <%= form.text_field :medico %>
  </div>

  <div class="field">
    <%= form.label :hospital %>
    <%= form.text_field :hospital %>
  </div>

  <div class="field">
    <%= form.label :coaseguro %>
    <%= form.text_field :coaseguro %>
  </div>

  <div class="field">
    <%= form.label :icd %>
    <%= form.number_field :icd %>
  </div>

  <div class="field">
    <%= form.label :ctp %>
    <%= form.number_field :ctp %>
  </div>

  <div class="field">
    <%= form.label :ctp2 %>
    <%= form.number_field :ctp2 %>
  </div>

  <div class="field">
    <%= form.label :folio %>
    <%= form.number_field :folio %>
  </div>

  <div class="field">
    <%= form.label :reclamacion %>
    <%= form.text_field :reclamacion %>
  </div>

  <div class="field">
    <%= form.label :ingreso %>
    <%= form.text_field :ingreso %>
  </div>

  <div class="field">
    <%= form.label :solicitud %>
    <%= form.text_field :solicitud %>
  </div>

  <div class="field">
    <%= form.label :fecha_even %>
    <%= form.text_field :fecha_even %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entregas/edit.html.erb
<h1>Editing Entrega</h1>

<%= render 'form', entrega: @entrega %>

<%= link_to 'Show', @entrega %> |
<%= link_to 'Back', entregas_path %>

app/views/entregas/entrega.pdf.erb
<div class="image-head">
  <%= wicked_pdf_image_tag 'head'%>
</div>

<div class="row my-5">
  <table>
    <tr>
      <td class="col-md-7"></td>
      <td class="col-md-5">
        
        <table class="table-date">
          <tr>
            <td>
              <div>FECHA DE IMPRESIÓN:</div>
            </td>
            <td>
              <%= date = Time.now%>
              <%= puts date.strftime("%d-%m-%Y %H:%M:%S")%>
            </td>
          </tr>
        </table>

      </td>
    </tr>
  </table>
  </section>
</div>

<% @entregas.each do |person| %>

<div class="my-5">
  <table class="col-md-12 bg-light">
    <tr>
      <td class="px-3">
        <div>
          <table class="mini-table">
            <tr>
              <td class="mini-table-static">
                <div>Ticket:</div>
              </td>
              <td>
                <div>
                  <%= person.ticket %>    
                </div>
              </td>
            </tr>
          </table>
        </div>

        <div class="my-2">
          <div>Asegurado</div>
          <section class="border border-dark  form-control bg-light mx-1">
            <%= person.asegurado %>    
          </section>
        </div>

        <div class="my-3">
          <table class="mini-table">
            <tr>
              <td class="mini-table-static-large">
                <div>Medico Tratante:</div> 
              </td>
              <td>
                <div>
                  <%= person.medico %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

        <div class="my-2">
          <table class="mini-table">
            <tr>
              <td class="mini-table-static">
                <div>Hospital:</div> 
              </td>
              <td>
                <div>
                  <%= person.hospital %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

        <div>
          <table class="mini-table my-3">
            <tr>
              <td class="mini-table-static">
                <div>Coaseguro:</div> 
              </td>
              <td>
                <div>
                  <%= person.coaseguro %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

        <hr>

        <div>
          <table class="mini-table">
            <tr>
              <td class="mini-table-static-small">
                <div>ICD:</div> 
              </td>
              <td>
                <div>
                  <%= person.icd %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

        <div class="my-2">
          <table class="mini-table">
            <tr>
              <td class="mini-table-static-small">
                <div>CPT:</div> 
              </td>
              <td>
                <div>
                  <%= person.ctp %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

        <div class="my-2">
          <table class="mini-table">
            <tr>
              <td class="mini-table-static-small">
                <div>CPT:</div> 
              </td>
              <td>
                <div>
                  <%= person.ctp2 %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

      </td>

      <td class="px-3"> 
        <div>
          <div>Folio GNP Hospitalización</div>
          <section class="border border-dark form-control bg-light mx-1">
            <%= person.folio %> 
          </section>
        </div>

        <div class="my-3">
          <div>Reclamación</div>
          <section class="border border-dark form-control bg-light mx-1">
            <%= person.reclamacion %> 
          </section>
        </div>

        <div>
          <div>Fecha Probable de ingreso</div>
          <section class="border border-dark form-control bg-light mx-1">
            <%= person.ingreso %> 
          </section>
        </div>

        <div class="my-3">
          <table class="mini-table">
            <tr>
              <td class="mini-table-static-large">
                <div>Solicitud Origen:</div> 
              </td>
              <td>
                <div>
                  <%= person.solicitud %> 
                </div> 
              </td>
            </tr>
          </table>
        </div>

        <div class="my-3">
          <div>Fecha de evento quírurgico</div>
          <section class="border border-dark form-control bg-light mx-1">
            <%= person.fecha_even %> 
          </section>
        </div>
      </td>
    </tr>
  </table>
</div>
<% end %>

app/views/entregas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entregas</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Asegurado</th>
      <th>Medico</th>
      <th>Hospital</th>
      <th>Coaseguro</th>
      <th>Icd</th>
      <th>Ctp</th>
      <th>Ctp2</th>
      <th>Folio</th>
      <th>Reclamacion</th>
      <th>Ingreso</th>
      <th>Solicitud</th>
      <th>Fecha even</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entregas.each do |entrega| %>
      <tr>
        <td><%= entrega.ticket %></td>
        <td><%= entrega.asegurado %></td>
        <td><%= entrega.medico %></td>
        <td><%= entrega.hospital %></td>
        <td><%= entrega.coaseguro %></td>
        <td><%= entrega.icd %></td>
        <td><%= entrega.ctp %></td>
        <td><%= entrega.ctp2 %></td>
        <td><%= entrega.folio %></td>
        <td><%= entrega.reclamacion %></td>
        <td><%= entrega.ingreso %></td>
        <td><%= entrega.solicitud %></td>
        <td><%= entrega.fecha_even %></td>
        <td><%= link_to 'Show', entrega %></td>
        <td><%= link_to 'Edit', edit_entrega_path(entrega) %></td>
        <td><%= link_to 'Destroy', entrega, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entrega', new_entrega_path %>

app/views/entregas/new.html.erb
<h1>New Entrega</h1>

<%= render 'form', entrega: @entrega %>

<%= link_to 'Back', entregas_path %>

app/views/entregas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @entrega.ticket %>
</p>

<p>
  <strong>Asegurado:</strong>
  <%= @entrega.asegurado %>
</p>

<p>
  <strong>Medico:</strong>
  <%= @entrega.medico %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @entrega.hospital %>
</p>

<p>
  <strong>Coaseguro:</strong>
  <%= @entrega.coaseguro %>
</p>

<p>
  <strong>Icd:</strong>
  <%= @entrega.icd %>
</p>

<p>
  <strong>Ctp:</strong>
  <%= @entrega.ctp %>
</p>

<p>
  <strong>Ctp2:</strong>
  <%= @entrega.ctp2 %>
</p>

<p>
  <strong>Folio:</strong>
  <%= @entrega.folio %>
</p>

<p>
  <strong>Reclamacion:</strong>
  <%= @entrega.reclamacion %>
</p>

<p>
  <strong>Ingreso:</strong>
  <%= @entrega.ingreso %>
</p>

<p>
  <strong>Solicitud:</strong>
  <%= @entrega.solicitud %>
</p>

<p>
  <strong>Fecha even:</strong>
  <%= @entrega.fecha_even %>
</p>

<%= link_to 'Edit', edit_entrega_path(@entrega) %> |
<%= link_to 'Back', entregas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pdf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/entrega.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">	
	<%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	<title></title>

	<%= wicked_pdf_stylesheet_link_tag 'entregas' %>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body class="container-fluid">
	<%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :pricing %>
    <%= form.number_field :pricing %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/entrega.pdf.erb
	<table>
		<thead>
			<tr>
				<th>
					Titulo
				</th>
				<th>
					Precio
				</th>
			</tr>
		</thead>

		<tbody>
			<% @products.each do |product| %>
			<tr>
				<td>
					<%= product.title%>
				</td>
				<td>
					<%= product.pricing%>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Pricing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.pricing %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Pricing:</strong>
  <%= @product.pricing %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>